### ISSUE TITLE
feat: Remove Extends From Class Mixed

### ISSUE THREAD

**Issue by Isaque-Claudino-dos-Santos** [Isaque-Claudino-dos-Santos/ts-game-script#52]
### TODO
- [ ] remove `extends Geometry` in class
- [ ] add attribute `x: number`
- [ ] add attribute `y: number`
- [ ] add method `moveTo(x,y)`
- [ ] add method `tranlateX(x)`
- [ ] add method `tranlateY(y)`
- [ ] add method `draw( context)`
