### ISSUE TITLE
feat: Ajust Methods in Geometry Class

### ISSUE THREAD

**Issue by Isaque-Claudino-dos-Santos** [Isaque-Claudino-dos-Santos/ts-game-script#53]
### TODO

- [ ] rename method `addX` to `tranlateX`
- [ ] rename method `addY` to `translateY`
- [ ] rename method `fixTo` to `fixedTo`
- [ ] add method `setLineWidth`
